services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_DATABASE: delivery_db
      MYSQL_USER: delivery
      MYSQL_PASSWORD: delivery_secret
    ports:
      - "3307:3306"
    volumes:
      - delivery_mysql_data:/var/lib/mysql

volumes:
  delivery_mysql_data:
